"""empty message

Revision ID: 043b338eb7f8
Revises: 
Create Date: 2019-12-16 15:24:08.957826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '043b338eb7f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
