"""empty message

Revision ID: 98df3a287f02
Revises: 
Create Date: 2019-12-15 16:21:12.330326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98df3a287f02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tokens', ['uuid'])
    op.alter_column('users', 'mobile',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('users', 'mobile',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'tokens', type_='unique')
    # ### end Alembic commands ###
